index/urls.py
from django.urls import path

from . import views

app_name = "index"
urlpatterns = [
    path("", views.HomePage, name="HomePage"),
    path('assignments/', views.GameList, name='GameList'),
    path('game/<int:game_id>/<int:word_list_id>/', views.GamePage, name='GamePage'),
    path('assignments/lists/add', views.AssignmentCreationPage, name='AssignmentCreationPage'),
    path('assignments/done/', views.CreateAssignment, name='CreateAssignment'),
    path("assignments/list/<int:assignment_list_id>/add", views.AddAssignments, name="AddAssignments"),
    path("assignments/list/<int:assignment_list_id>/adding", views.AddAssignmentToSQL, name="AddAssignmentToSQL"),
    path("assignments/list/<int:assignment_list_id>/remove/<int:assignment_id>/", views.RemoveAssignmentSQL, name="RemoveAssignmentSQL"),
    path("assignments/lists/", views.AssignmentLists, name="AssignmentLists"),
    path("assignments/list/<int:assignment_list_id>/remove/", views.AssignmentListRemove, name="AssignmentListRemove"),
]

languagebean/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("index.urls"), name="index"),
    path('accounts/', include('django.contrib.auth.urls')),
]

index/models.py
from django.db import models
from django.contrib.auth.models import User

class Game(models.Model):
    game_name = models.CharField(max_length=20, default="Multiple Choice")
    game_contents = models.CharField(max_length=1000, default="""
<h1 id="original_word">Original word</h1>
<div id="score">Score: 0</div>
<div id="center-container">
    <div id="container">
        <button class="option" onclick="choose(0);" id="button0">Translated word</button>
        <button class="option" onclick="choose(1);" id="button1">Translated word</button>
        <button class="option" onclick="choose(2);" id="button2">Translated word</button>
        <button class="option" onclick="choose(3);" id="button3">Translated word</button>
    </div>
    <div id="win" style="display:none;">You won!</div>
</div>""")

class WordList(models.Model):
    name = models.CharField(max_length=20, default="Word List")
    original_language = models.CharField(max_length=20)
    translated_language = models.CharField(max_length=20)

class Word(models.Model):
    word_list = models.ForeignKey(WordList, on_delete=models.CASCADE)
    original_word = models.CharField(max_length=20)
    translated_word = models.CharField(max_length=20)

    def __str__(self):
        return self.word_list.original_language+": "+self.original_word+", "+self.word_list.translated_language+": "+self.translated_word

class UserGroup(models.Model):
    name = models.CharField(max_length=20)
    teacher = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name + ", Teacher: " + self.teacher.username

class StudentOfUserGroup(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    user_group = models.ForeignKey(UserGroup, on_delete=models.CASCADE)

class AssignmentList(models.Model):
    set_by = models.ForeignKey(User, on_delete=models.CASCADE)
    set_to = models.ForeignKey(UserGroup, on_delete=models.CASCADE)
    due_date = models.DateField("Date due")

class Assignment(models.Model):
    word_list = models.ForeignKey(WordList, on_delete=models.CASCADE)
    assignment_list = models.ForeignKey(AssignmentList, on_delete=models.CASCADE)
    game = models.ForeignKey(Game, on_delete=models.CASCADE)

index/views.py
from django.shortcuts import render
from django.http import Http404, HttpResponse, HttpResponseRedirect, HttpResponseForbidden
from django.templatetags.static import static
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout

from .models import *

def GameList(request):
    if request.user.is_authenticated:
        assignment_lists = AssignmentList.objects.filter(set_to__studentofusergroup__user=request.user)
        return render(request, "index/game_list.html", {"assignment_lists":assignment_lists})
    else:
        return HttpResponseForbidden("You need to be logged in to access this page")

def GamePage(request, game_id, word_list_id):
    word_list = WordList.objects.get(pk=word_list_id)
    game = Game.objects.get(pk=game_id)
    stylesheet = static("index/game"+str(game.pk)+".css")
    script = static("index/game"+str(game.pk)+".js")
    return render(request, "index/game.html", {"word_list":word_list, "game":game, "script":script, "stylesheet":stylesheet})

def HomePage(request):
    return render(request, "index/index.html", {"login":1 if request.user.is_authenticated else 0, "teacher":request.user.has_perm("index.add_assignmentlist"), "student":(not request.user.has_perm("index.add_assignmentlist")) and request.user.is_authenticated})

def AssignmentCreationPage(request):
    if request.user.is_authenticated and request.user.has_perm("index.add_assignmentlist"):
        classes = UserGroup.objects.filter(teacher=request.user)
        return render(request, "index/create_assignment.html", {"classes":classes})
    else:
        return HttpResponseForbidden("You need to be logged in and a teacher to access this page")

def CreateAssignment(request):
    assignment = AssignmentList(set_by=request.user, set_to=UserGroup.objects.get(pk=request.POST['class']), due_date=request.POST["due"])
    assignment.save()
    return HttpResponseRedirect(reverse("index:AddAssignments",kwargs={"assignment_list_id":assignment.pk}))

def AddAssignments(request, assignment_list_id):
    try:
        assignmentList = AssignmentList.objects.get(pk=assignment_list_id)
    except:
        return HttpResponseForbidden("This assignment list does not exist")
    if not request.user.is_authenticated or not request.user.has_perm("index.add_assignmentlist"):
        return HttpResponseForbidden("You need to be logged in and a teacher to access this page")
    if assignmentList.set_by != request.user:
        return HttpResponseForbidden("You have not made this assignment list.")
    Games = Game.objects.all()
    WordLists = WordList.objects.all()
    return render(request, "index/add_assignments.html", {"list": assignmentList, "Games":Games, "WordLists":WordLists})
    
def AddAssignmentToSQL(request, assignment_list_id):
    try:
        assignmentList = AssignmentList.objects.get(pk=assignment_list_id)
    except:
        return HttpResponseForbidden("This assignment list does not exist")
    if not request.user.is_authenticated or not request.user.has_perm("index.add_assignmentlist"):
        return HttpResponseForbidden("You need to be logged in and a teacher to access this page")
    if assignmentList.set_by != request.user:
        return HttpResponseForbidden("You have not made this assignment list.")
    
    assignment = Assignment(word_list=WordList.objects.get(pk=request.POST["wordlist"]),
                            assignment_list=assignmentList,
                            game=Game.objects.get(pk=request.POST["game"]))
    assignment.save()
    return HttpResponseRedirect(reverse("index:AddAssignments", kwargs={"assignment_list_id":assignment_list_id}))

def RemoveAssignmentSQL(request, assignment_list_id, assignment_id):
    assignment = Assignment.objects.get(pk=assignment_id)
    if assignment.assignment_list.set_by != request.user:
        return HttpResponseForbidden("You have not made this assignment list.")
    elif assignment.assignment_list != AssignmentList.objects.get(pk=assignment_list_id):
        return HttpResponseForbidden("This assignment is not part of this assignment list.")
    
    assignment.delete()
    return HttpResponseRedirect(reverse("index:AddAssignments", kwargs={"assignment_list_id":assignment_list_id}))

def AssignmentLists(request):
    if request.user.is_authenticated and request.user.has_perm("index.add_assignmentlist"):
        assignment_lists = AssignmentList.objects.filter(set_by=request.user)
        return render(request, "index/assignment_lists.html", {"lists":assignment_lists})
    else:
        return HttpResponseForbidden("You need to be logged in and a teacher to access this page")

def AssignmentListRemove(request, assignment_list_id):
    assignment_list = AssignmentList.objects.get(pk=assignment_list_id)
    if assignment_list.set_by != request.user:
        return HttpResponseForbidden("You have not made this assignment list.")
    
    assignment_list.delete()
    return HttpResponseRedirect(reverse("index:AssignmentLists"))

index/templates/index/add_assignments.html
{% extends "index/base.html" %}
{% block "title" %}Add assignments to assignment list{% endblock %}
{% block "contents" %}
<h1>Add assignments to assignment list</h1>
{% if list.assignment_set.all %}
<ul>
{% for assignment in list.assignment_set.all %}
<li>{{ assignment.game.game_name }} - {{ assignment.word_list.name }}: {{ assignment.word_list.original_language }} - {{ assignment.word_list.translated_language }} <a href="{% url "index:RemoveAssignmentSQL" assignment_list_id=list.pk assignment_id=assignment.pk %}">remove</a></li>
{% endfor %}
</ul>
{% else %}
This assignment list is empty
{% endif %}
<form method="post" action="{% url 'index:AddAssignmentToSQL' assignment_list_id=list.pk %}">
{% csrf_token %}
<label for="game">Game</label>
<select name="game" id="game">
{% for game in Games %}
    <option value="{{ game.pk }}">{{ game.game_name }}</option>
{% endfor %}
</select>
<label for="wordlist">Word list</label>
<select name="wordlist" id="wordlist">
{% for word_list in WordLists %}
    <option value="{{ word_list.pk }}">{{ word_list.name }}: {{ word_list.original_language }} - {{ word_list.translated_language }}</option>
{% endfor %}
</select>
<input type="submit" value="Add assignment">
</form>
{% endblock %}

index/templates/index/assignment_lists.html
{% extends "index/base.html" %}
{% load static %}
{% block "title" %}Assignment lists{% endblock %}
{% block "head" %}
<link rel="stylesheet" href="{% static "index/assignment_lists.css" %}">
{% endblock %}
{% block "contents" %}
<h1>Assignment lists</h1>
{% if lists %}
<ul>
{% for list in lists %}
<li><a href="{% url "index:AddAssignments" assignment_list_id=list.pk %}">Due: {{ list.due_date }}, Assignments: <ul>
{% for assignment in list.assignment_set.all %}
<li>{{ assignment.game.game_name }} - {{ assignment.word_list.name }}: {{ assignment.word_list.original_language }} - {{ assignment.word_list.translated_language }}</li>
{% endfor %}
</ul></a>
<a href="{% url "index:AssignmentListRemove" assignment_list_id=list.pk %}">remove</a>
</li>
{% endfor %}
</ul>
{% else %}
You have made no assignment lists.
{% endif %}
<a href="{% url "index:AssignmentCreationPage" %}">Add assignment</a>
{% endblock %}

index/templates/index/base.html
{% load static %}
<!Doctype html>
<html>
    <head>
        <link rel="favicon" type="image/jpg" href="{% block "favicon" %}{% static "index/favicon.jpg" %}{% endblock %}">
        <link rel="stylesheet" href="{% static "index/style.css" %}">
        <title>{% block "title" %}configured incorrectly{% endblock %}・languagebean</title>
        {% block "head" %}
        {% endblock %}
    </head>
    <body>
        {% block "contents" %}
        <h1>Oops! This is configured incorrectly!</h1>
        {% endblock %}
    </body>
</html>

index/templates/index/create_assignment.html
{% extends "index/base.html" %}
{% block "title" %}Create assignment{% endblock %}
{% block "contents" %}
<h1>Create assignment</h1>
<form method="post" action="{% url 'index:CreateAssignment' %}">
{% csrf_token %}
<label for="due">Due date</label><br />
<input type="date" id="due" name="due"><br />
<label>Class:</label><br />
{% for class in classes %}
<input type="radio" id="class{{ forloop.counter0 }}" name="class" value="{{ class.id }}">
<label for="class{{ forloop.counter0 }}">{{ class.name }}</label><br />
{% endfor %}
<input type="submit" value="create">
</form>
{% endblock %}

index/templates/index/game.html
{% extends "index/base.html" %}
{% load static %}
{% block "title" %}{{ game.game_name }}{% endblock %}

{% block "head" %}
<script>
var original_words = [
{% for word in word_list.word_set.all %}"{{ word.original_word }}",{% endfor %}
]
var translated_words = [
{% for word in word_list.word_set.all %}"{{ word.translated_word }}",{% endfor %}
]
game_id = {{ game.pk }};
</script>
<link rel="stylesheet" href="{{ stylesheet }}">
{% endblock %}

{% block "contents" %}
{{ game.game_contents | safe }}
<script src="{{ script }}"></script>
{% endblock %}

index/templates/index/game_list.html
{% extends "index/base.html" %}
{% block "title" %}Assignments{% endblock %}
{% block "contents" %}
<ul>
    {% for assignment_list in assignment_lists %}
        <h1>Due: {{ assignment_list.due_date }} Set by: {% if assignment_list.set_by.first_name != "" and assignment_list.set_by.last_name != "" %}{{ assignment_list.set_by.first_name }} {{ assignment_list.set_by.last_name }}{% else %}{{ assignment_list.set_by.username }}{% endif %}</h1>
        {% for assignment in assignment_list.assignment_set.all %}
        <li><a href="{% url "index:GamePage" game_id=assignment.game.pk word_list_id=assignment.word_list.pk %}">{{ assignment.game.game_name }} - {{ assignment.word_list.original_language }}-{{ assignment.word_list.translated_language }} {{ assignment.word_list.name }}</a></li>
        {% endfor %}
    {% endfor%}
</ul>
{% endblock %}

index/templates/index/index.html
{% extends "index/base.html" %}
{% block "title" %}Home{% endblock %}
{% block "contents" %}
<h1 style="font-size:5rem;margin-bottom:0.2rem;">Languagebean</h1>
<h1 style="font-size:1.5rem;margin-top:0;"><a href="//languagenut.com">Languagenut</a> but better</h2>
{% if teacher %}
<h2><a href="{% url "index:AssignmentLists" %}">Assignment lists</a></h2>
{% elif student %}
<h2><a href="{% url "index:GameList" %}">Assignment list</a></h2>
{% endif %}
{% if login == 1 %}
<h2><a href="{% url "logout" %}">Log out</a></h2>
{% else %}
<h2><a href="{% url "login" %}">Log in</a></h2>
{% endif %}
{% endblock %}